import tseslint from 'typescript-eslint';
import obsidianmd from "eslint-plugin-obsidianmd";
// Not re-exported from the package root, so this is a deep import. If a
// plugin upgrade moves the file, the config fails to load — loud, not silent.
import { DEFAULT_ACRONYMS } from "eslint-plugin-obsidianmd/dist/lib/rules/ui/acronyms.js";
import globals from "globals";
import { globalIgnores } from "eslint/config";
// Side-effect import: patches util.styleText on Node < 20.12 so the default
// formatter does not crash when a run has findings to print.
import "./scripts/styletext-polyfill.mjs";

export default tseslint.config(
	{
		languageOptions: {
			globals: {
				...globals.browser,
				// Node.js globals needed for desktop-only plugin (isDesktopOnly: true)
				require: "readonly",
				process: "readonly",
				Buffer: "readonly",
				__dirname: "readonly",
				__filename: "readonly",
				module: "readonly",
				exports: "readonly",
			},
			parserOptions: {
				projectService: {
					allowDefaultProject: [
						'eslint.config.mts',
						'manifest.json'
					]
				},
				tsconfigRootDir: import.meta.dirname,
				extraFileExtensions: ['.json']
			},
		},
	},
	...obsidianmd.configs.recommended,
	{
		files: ["**/*.ts"],
		rules: {
			// Comma-first: the comma leads the next line instead of trailing
			// the previous one. Cleanest diffs — adding an item touches only
			// its own line. comma-spacing pairs with it: one space between
			// the leading comma and the item.
			"comma-style": ["error", "first"],
			"comma-spacing": ["error", { before: false, after: true }],
			// Enable auto-fix for sentence case UI text. The acronyms option
			// REPLACES the rule's built-in list, so the defaults are spread back
			// in — MCP is the project addition.
			"obsidianmd/ui/sentence-case": ["error", { allowAutoFix: true, acronyms: [...DEFAULT_ACRONYMS, "MCP"] }],
		},
	},
	// builtin-modules is build-tooling only (esbuild.config.mjs), not plugin code.
	// js-yaml is used for YAML parsing in Bases API — no built-in alternative exists.
	//
	// obsidianmd >= 0.3.0 wires its typed plugin rules into the hybrid recommended
	// config without a `**/*.ts` files scope, so ESLint also tries to run them on
	// package.json (which uses the JSON language and has no parser services). The
	// rules call getParserServices() and abort the whole run. Disable the typed
	// rules here for the JSON files the recommended config inspects.
	{
		files: ["package.json", "**/*.json"],
		rules: {
			"depend/ban-dependencies": "off",
			"obsidianmd/no-plugin-as-component": "off",
			"obsidianmd/no-view-references-in-plugin": "off",
			"obsidianmd/no-unsupported-api": "off",
			"obsidianmd/prefer-file-manager-trash-file": "off",
			"obsidianmd/prefer-instanceof": "off",
		},
	},
	globalIgnores([
		"node_modules",
		"dist",
		"tests",
		// Generated by `make coverage` — istanbul's HTML report ships its own vendored
		// JS, which is not project code and has no tsconfig entry.
		"coverage",
		"test-*.js",
		"*.config.js",
		"*.config.mjs",
		"esbuild.config.mjs",
		"eslint.config.mts",
		"jest.config.js",
		"versions.json",
		"main.js",
		"worker.js",
		"mcpb",
		"scripts",
		// Data files — obsidianmd's recommended config only wires the JSON
		// language to package.json; other .json files fall through to the JS
		// parser and fail with "Unexpected token :". They aren't code anyway.
		// (The validate-manifest rule reads manifest.json directly via fs.)
		"tsconfig.json",
		"package-lock.json",
		"manifest.json",
		"versions.json",
		".claude/**",
	]),
);
